name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "./ansible/playbooks/*.yml"
        override-deps: |
          ansible==2.11.5
          ansible-lint==5.2.0
        args: "-c ./ansible/.ansible-lint"
