---

name: Terraform validate

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: terraform

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.31

    - name: Terraform Init Stage
      id: init_stage
      run: terraform init -backend=false
      working-directory: ./terraform/stage

    - name: Terraform Validate Stage
      id: validate_stage
      run: terraform validate -var-file=terraform.tfvars.example
      working-directory: ./terraform/stage

    - name: Terraform Init Prod
      id: init_prod
      run: terraform init -backend=false
      working-directory: ./terraform/prod

    - name: Terraform Validate Prod
      id: validate_prod
      run: terraform validate -var-file=terraform.tfvars.example
      working-directory: ./terraform/prod
